import type { AppState, Item, Offer, User } from "./types";

const img = (id: string, w = 800) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=70`;

export const DEMO_USER_ID = "u-me";

const users: User[] = [
  {
    id: DEMO_USER_ID,
    username: "cenma",
    name: "Carlos Enmanuel",
    email: "cenma@mecuadra.cu",
    avatar: "https://i.pravatar.cc/160?img=12",
    bio: "Truequeo en Plaza y Vedado. Busco alimentos y aseo.",
    province: "La Habana",
    municipality: "Plaza de la Revolución",
    neighborhood: "Vedado",
    transport: "tengo",
    ratingAvg: 4.9,
    ratingCount: 11,
    tradesCompleted: 14,
    verified: true,
    createdAt: "2026-03-12T10:00:00.000Z",
  },
  {
    id: "u-paloma",
    username: "paloma",
    name: "Paloma",
    email: "paloma@mecuadra.cu",
    avatar: "https://i.pravatar.cc/160?img=32",
    bio: "Plaza. Intercambio medicamentos y artículos del hogar.",
    province: "La Habana",
    municipality: "Plaza de la Revolución",
    neighborhood: "Vedado",
    transport: "sin",
    ratingAvg: 4.8,
    ratingCount: 23,
    tradesCompleted: 31,
    verified: true,
    createdAt: "2026-01-08T10:00:00.000Z",
  },
  {
    id: "u-patricia",
    username: "patricia",
    name: "Patricia",
    email: "patricia@mecuadra.cu",
    avatar: "https://i.pravatar.cc/160?img=47",
    bio: "Me desplazo. Busco hidroclorotiazida.",
    province: "La Habana",
    municipality: "Playa",
    neighborhood: "Miramar",
    transport: "voy",
    ratingAvg: 5,
    ratingCount: 8,
    tradesCompleted: 9,
    verified: true,
    createdAt: "2026-04-02T10:00:00.000Z",
  },
  {
    id: "u-miriam",
    username: "miriam",
    name: "Miriam Prieto",
    email: "miriam@mecuadra.cu",
    avatar: "https://i.pravatar.cc/160?img=20",
    bio: "Cerro. Trueque de aseo.",
    province: "La Habana",
    municipality: "Cerro",
    neighborhood: "Casino Deportivo",
    transport: "sin",
    ratingAvg: 4.6,
    ratingCount: 6,
    tradesCompleted: 7,
    verified: false,
    createdAt: "2026-05-14T10:00:00.000Z",
  },
  {
    id: "u-yabo",
    username: "yabocita",
    name: "Yabo",
    email: "yabo@mecuadra.cu",
    avatar: "https://i.pravatar.cc/160?img=15",
    bio: "Víbora. Sin transporte, debe venir a casa.",
    province: "La Habana",
    municipality: "Diez de Octubre",
    neighborhood: "La Víbora",
    transport: "sin",
    ratingAvg: 4.4,
    ratingCount: 12,
    tradesCompleted: 16,
    verified: true,
    createdAt: "2025-11-20T10:00:00.000Z",
  },
  {
    id: "u-lari",
    username: "lari",
    name: "Lari",
    email: "lari@mecuadra.cu",
    avatar: "https://i.pravatar.cc/160?img=45",
    bio: "Cerro. Aseo por medicamentos y comida.",
    province: "La Habana",
    municipality: "Cerro",
    neighborhood: "El Cerro",
    transport: "sin",
    ratingAvg: 4.7,
    ratingCount: 19,
    tradesCompleted: 22,
    verified: true,
    createdAt: "2025-09-01T10:00:00.000Z",
  },
  {
    id: "u-sury",
    username: "sury",
    name: "Sury",
    email: "sury@mecuadra.cu",
    avatar: "https://i.pravatar.cc/160?img=24",
    bio: "Arroyo Naranjo, Managua.",
    province: "La Habana",
    municipality: "Arroyo Naranjo",
    neighborhood: "Managua",
    transport: "tengo",
    ratingAvg: 4.5,
    ratingCount: 4,
    tradesCompleted: 5,
    verified: false,
    createdAt: "2026-02-11T10:00:00.000Z",
  },
  {
    id: "u-lili",
    username: "lili",
    name: "Lili",
    email: "lili@mecuadra.cu",
    avatar: "https://i.pravatar.cc/160?img=5",
    bio: "Playa. Cigarros por café.",
    province: "La Habana",
    municipality: "Playa",
    neighborhood: "Buena Vista",
    transport: "tengo",
    ratingAvg: 4.9,
    ratingCount: 15,
    tradesCompleted: 18,
    verified: true,
    createdAt: "2026-01-22T10:00:00.000Z",
  },
  {
    id: "u-21o",
    username: "veintiuno",
    name: "21o",
    email: "21o@mecuadra.cu",
    avatar: "https://i.pravatar.cc/160?img=68",
    bio: "Plaza. Ibuprofeno por alimentos o aseo.",
    province: "La Habana",
    municipality: "Plaza de la Revolución",
    neighborhood: "Vedado",
    transport: "voy",
    ratingAvg: 4.3,
    ratingCount: 3,
    tradesCompleted: 3,
    verified: false,
    createdAt: "2026-07-30T10:00:00.000Z",
  },
];

const items: Item[] = [
  {
    id: "i-me-1",
    userId: DEMO_USER_ID,
    title: "Detergente en polvo 1 kg",
    description: "Bolsa de detergente sellada, de tienda.",
    category: "aseo",
    condition: "sellado",
    photos: [img("photo-1563453392212-326f5e854473"), img("photo-1584305574647-0cc949a4b025")],
    status: "activo",
    createdAt: "2026-08-10T12:00:00.000Z",
  },
  {
    id: "i-me-2",
    userId: DEMO_USER_ID,
    title: "Aceite 1 L sellado",
    description: "Aceite de cocina sellado.",
    category: "alimentos",
    condition: "sellado",
    photos: [img("photo-1474979266404-7eaacbcd87c5")],
    status: "activo",
    createdAt: "2026-08-12T12:00:00.000Z",
  },
  {
    id: "i-me-3",
    userId: DEMO_USER_ID,
    title: "Jabón de baño Palmolive",
    description: "3 unidades nuevas.",
    category: "aseo",
    condition: "nuevo",
    photos: [img("photo-1584305574647-0cc949a4b025")],
    status: "activo",
    createdAt: "2026-08-14T12:00:00.000Z",
  },
  {
    id: "i-me-4",
    userId: DEMO_USER_ID,
    title: "Pasta dental",
    description: "Tubo nuevo, sin abrir.",
    category: "cuidado",
    condition: "nuevo",
    photos: [img("photo-1559591935-c6c92ca44dd8")],
    status: "activo",
    createdAt: "2026-08-15T12:00:00.000Z",
  },
  {
    id: "i-pal-1",
    userId: "u-paloma",
    title: "Carterita roja nueva",
    description: "Bolso pequeño rojo, nunca usado.",
    category: "ropa",
    condition: "nuevo",
    photos: [img("photo-1584917865442-de89df76afd3"), img("photo-1590874103328-eac38a941379")],
    status: "activo",
    createdAt: "2026-08-16T12:00:00.000Z",
  },
  {
    id: "i-pal-2",
    userId: "u-paloma",
    title: "Bermuda de hombre talla 32",
    description: "Nueva, con etiqueta.",
    category: "ropa",
    condition: "nuevo",
    photos: [img("photo-1591195853828-11db59a44d6b")],
    status: "activo",
    createdAt: "2026-08-16T12:05:00.000Z",
  },
  {
    id: "i-pal-3",
    userId: "u-paloma",
    title: "Juego de 6 vasos nuevos",
    description: "Vidrio, sin uso.",
    category: "hogar",
    condition: "nuevo",
    photos: [img("photo-1513558161293-cdaf765ed2fd")],
    status: "activo",
    createdAt: "2026-08-16T12:10:00.000Z",
  },
  {
    id: "i-pal-4",
    userId: "u-paloma",
    title: "Lisinopril + vitamina D3 y E",
    description: "Lote de medicamentos: lisinopril, vitamina D3, vitamina E, furosemida, atenolol, ácido fólico. Preguntar existencias.",
    category: "medicamentos",
    condition: "sellado",
    photos: [img("photo-1584308666744-24d5c474f2ae"), img("photo-1471864190281-a93a3070b6de")],
    status: "activo",
    createdAt: "2026-08-17T12:00:00.000Z",
  },
  {
    id: "i-pat-1",
    userId: "u-patricia",
    title: "Lo que acordemos",
    description: "Tengo flexibilidad. Dime qué necesitas y vemos si me cuadra.",
    category: "otros",
    condition: "nuevo",
    photos: [img("photo-1556742049-0cfed4f6a45d")],
    status: "activo",
    createdAt: "2026-08-17T08:00:00.000Z",
  },
  {
    id: "i-mir-1",
    userId: "u-miriam",
    title: "Suavizador Bambú",
    description: "Suavizante de ropa Bambú, casi lleno.",
    category: "aseo",
    condition: "usado",
    photos: [img("photo-1610557892470-55d9e80c0bce")],
    status: "activo",
    createdAt: "2026-08-17T15:00:00.000Z",
  },
  {
    id: "i-yabo-1",
    userId: "u-yabo",
    title: "Lote de aseo y despensa",
    description: "Espaguetis, lentejas, ketchup, mayonesa, champú Sedal naranja, jabón Palmolive, chocolate de tienda, colonia violeta, cuchillas.",
    category: "aseo",
    condition: "nuevo",
    photos: [img("photo-1608571423902-eed4a5ad8108"), img("photo-1621996346565-e3dbc646d9a9")],
    status: "activo",
    createdAt: "2026-08-11T10:00:00.000Z",
  },
  {
    id: "i-lari-1",
    userId: "u-lari",
    title: "Detergente, Rexona y jabón puro",
    description: "Detergente de varios tipos, desodorante Rexona, jabón puro y frazada de piso.",
    category: "aseo",
    condition: "nuevo",
    photos: [img("photo-1563453392212-326f5e854473"), img("photo-1631729371254-42c2892f0e6e")],
    status: "activo",
    createdAt: "2026-08-09T10:00:00.000Z",
  },
  {
    id: "i-lari-2",
    userId: "u-lari",
    title: "Aceite de cocina",
    description: "Pomo de aceite sellado.",
    category: "alimentos",
    condition: "sellado",
    photos: [img("photo-1474979266404-7eaacbcd87c5")],
    status: "activo",
    createdAt: "2026-08-09T10:10:00.000Z",
  },
  {
    id: "i-sury-1",
    userId: "u-sury",
    title: "Spaghetti",
    description: "Paquetes de spaghetti de tienda.",
    category: "alimentos",
    condition: "sellado",
    photos: [img("photo-1621996346565-e3dbc646d9a9")],
    status: "activo",
    createdAt: "2026-08-08T10:00:00.000Z",
  },
  {
    id: "i-lili-1",
    userId: "u-lili",
    title: "Cigarros criollos · 4 cajas",
    description: "4 cajas de criollos. Trueque, no venta.",
    category: "tabaco",
    condition: "sellado",
    photos: [img("photo-1595854341625-f33ee10dbf94")],
    status: "activo",
    createdAt: "2026-08-13T10:00:00.000Z",
  },
  {
    id: "i-21-1",
    userId: "u-21o",
    title: "Ibuprofeno 200 mg · 100 tabletas",
    description: "Frasco de 100 tabletas de ibuprofeno 200 mg.",
    category: "medicamentos",
    condition: "sellado",
    photos: [img("photo-1584308666744-24d5c474f2ae")],
    status: "activo",
    createdAt: "2026-08-18T08:00:00.000Z",
  },
];

const offers: Offer[] = [
  {
    id: "o-pal-hogar",
    userId: "u-paloma",
    itemIds: ["i-pal-1", "i-pal-2", "i-pal-3"],
    wants: [{ title: "Escucho propuestas", category: "abierto" }],
    openToProposals: true,
    message: "Carterita, bermuda 32 y vasos. Vedado.",
    province: "La Habana",
    municipality: "Plaza de la Revolución",
    neighborhood: "Vedado",
    transport: "sin",
    status: "abierta",
    featured: true,
    views: 128,
    createdAt: "2026-08-16T17:11:00.000Z",
  },
  {
    id: "o-pal-med",
    userId: "u-paloma",
    itemIds: ["i-pal-4"],
    wants: [
      { title: "Pomada cicatrizante", category: "medicamentos" },
      { title: "Pentoxifilina / diosmina", category: "medicamentos" },
      { title: "Leche en polvo, aceite o cárnicos", category: "alimentos" },
    ],
    openToProposals: true,
    message: "Tengo varios medicamentos. Priorizo pomada cicatrizante y alimentos.",
    province: "La Habana",
    municipality: "Plaza de la Revolución",
    neighborhood: "Vedado",
    transport: "sin",
    status: "abierta",
    featured: true,
    views: 86,
    createdAt: "2026-08-17T13:19:00.000Z",
  },
  {
    id: "o-pat",
    userId: "u-patricia",
    itemIds: ["i-pat-1"],
    wants: [{ title: "Hidroclorotiazida", category: "medicamentos" }],
    openToProposals: false,
    message: "Me desplazo al lugar. Busco específicamente hidroclorotiazida.",
    province: "La Habana",
    municipality: "Playa",
    neighborhood: "Miramar",
    transport: "voy",
    status: "abierta",
    featured: false,
    views: 44,
    createdAt: "2026-08-18T08:11:00.000Z",
  },
  {
    id: "o-mir",
    userId: "u-miriam",
    itemIds: ["i-mir-1"],
    wants: [{ title: "Escucho propuestas", category: "abierto" }],
    openToProposals: true,
    message: "Suavizador Bambú. Cerro.",
    province: "La Habana",
    municipality: "Cerro",
    neighborhood: "Casino Deportivo",
    transport: "sin",
    status: "abierta",
    featured: false,
    views: 19,
    createdAt: "2026-08-17T15:47:00.000Z",
  },
  {
    id: "o-yabo",
    userId: "u-yabo",
    itemIds: ["i-yabo-1"],
    wants: [{ title: "Cigarros criollos", category: "tabaco" }],
    openToProposals: true,
    message: "Lote de aseo y despensa. Sin transporte, 10/10, debe venir a casa.",
    province: "La Habana",
    municipality: "Diez de Octubre",
    neighborhood: "La Víbora",
    transport: "sin",
    status: "abierta",
    featured: false,
    views: 61,
    createdAt: "2026-08-11T16:00:00.000Z",
  },
  {
    id: "o-lari",
    userId: "u-lari",
    itemIds: ["i-lari-1"],
    wants: [
      { title: "Dipirona / paracetamol", category: "medicamentos" },
      { title: "Puré o pasta de tomate", category: "alimentos" },
      { title: "Crema para la piel", category: "cuidado" },
    ],
    openToProposals: false,
    message: "Aseo por medicamentos o comida. Cerro, sin transporte.",
    province: "La Habana",
    municipality: "Cerro",
    neighborhood: "El Cerro",
    transport: "sin",
    status: "abierta",
    featured: false,
    views: 37,
    createdAt: "2026-08-09T15:43:00.000Z",
  },
  {
    id: "o-lari-2",
    userId: "u-lari",
    itemIds: ["i-lari-2"],
    wants: [{ title: "Terbinafina o ketoconazol en crema", category: "medicamentos" }],
    openToProposals: false,
    message: "Aceite por antimicótico tópico.",
    province: "La Habana",
    municipality: "Cerro",
    neighborhood: "El Cerro",
    transport: "sin",
    status: "abierta",
    featured: false,
    views: 22,
    createdAt: "2026-08-09T15:45:00.000Z",
  },
  {
    id: "o-sury",
    userId: "u-sury",
    itemIds: ["i-sury-1"],
    wants: [{ title: "Cigarros criollos", category: "tabaco" }],
    openToProposals: false,
    message: "Spaghetti por criollos. Managua.",
    province: "La Habana",
    municipality: "Arroyo Naranjo",
    neighborhood: "Managua",
    transport: "tengo",
    status: "abierta",
    featured: false,
    views: 15,
    createdAt: "2026-08-08T15:40:00.000Z",
  },
  {
    id: "o-lili",
    userId: "u-lili",
    itemIds: ["i-lili-1"],
    wants: [{ title: "Café de la bodega (4 paqueticos)", category: "alimentos" }],
    openToProposals: true,
    message: "4 cajas de criollos por café. Me ajusto.",
    province: "La Habana",
    municipality: "Playa",
    neighborhood: "Buena Vista",
    transport: "tengo",
    status: "abierta",
    featured: true,
    views: 93,
    createdAt: "2026-08-13T17:05:00.000Z",
  },
  {
    id: "o-21",
    userId: "u-21o",
    itemIds: ["i-21-1"],
    wants: [
      { title: "Alimentos", category: "alimentos" },
      { title: "Aseo", category: "aseo" },
    ],
    openToProposals: true,
    message: "Ibuprofeno 200 mg (100 tabletas) por alimentos o aseo.",
    province: "La Habana",
    municipality: "Plaza de la Revolución",
    neighborhood: "Vedado",
    transport: "voy",
    status: "abierta",
    featured: false,
    views: 51,
    createdAt: "2026-08-18T11:04:00.000Z",
  },
];

export const seedState: AppState = {
  users,
  items,
  offers,
  trades: [
    {
      id: "t-demo",
      offerId: "o-21",
      ownerId: "u-21o",
      applicantId: DEMO_USER_ID,
      proposedItemIds: ["i-me-2"],
      proposalNote: "Te ofrezco el aceite 1L sellado por el ibuprofeno. Puedo ir a Vedado mañana.",
      status: "aceptado",
      ownerDelivered: false,
      applicantDelivered: false,
      ownerRated: false,
      applicantRated: false,
      createdAt: "2026-08-18T12:30:00.000Z",
      updatedAt: "2026-08-18T12:40:00.000Z",
    },
  ],
  messages: [
    {
      id: "m-1",
      tradeId: "t-demo",
      senderId: DEMO_USER_ID,
      text: "Hola, te ofrezco aceite sellado de 1L por el ibuprofeno. ¿Te cuadra?",
      createdAt: "2026-08-18T12:30:00.000Z",
    },
    {
      id: "m-2",
      tradeId: "t-demo",
      senderId: "u-21o",
      text: "Sí, me cuadra. ¿Puedes pasar por el parque de 21 y 8 mañana a las 5?",
      createdAt: "2026-08-18T12:36:00.000Z",
    },
    {
      id: "m-3",
      tradeId: "t-demo",
      senderId: DEMO_USER_ID,
      text: "Perfecto, ahí nos vemos.",
      createdAt: "2026-08-18T12:40:00.000Z",
    },
  ],
  notifications: [
    {
      id: "n-1",
      userId: DEMO_USER_ID,
      title: "21o aceptó tu trueque",
      body: "Ibuprofeno por aceite. Ya puedes coordinar el encuentro en el chat.",
      href: "/chat/t-demo",
      read: false,
      createdAt: "2026-08-18T12:40:00.000Z",
    },
    {
      id: "n-2",
      userId: DEMO_USER_ID,
      title: "Nueva oferta cerca de ti",
      body: "Paloma en Vedado escucha propuestas por una carterita y vasos.",
      href: "/oferta/o-pal-hogar",
      read: false,
      createdAt: "2026-08-16T17:20:00.000Z",
    },
  ],
  ratings: [],
  currentUserId: DEMO_USER_ID,
};
